language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -f ./client/Dockerfile.dev -t manishakhurana25/complex-multi-docker-test ./client
script:
  - docker run -e CI=true manishakhurana25/complex-multi-docker-test npm run test -- --coverage
#deploy:
#  provider: elasticbeanstalk
#  region: "ap-south-1"
#  app: "docker-react"
#  env: "DockerReact-env"
#  bucket_name: "elasticbeanstalk-ap-south-1-002152815032"
#  bucket_path: "docker-react"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: "$AWS_SECRET_KEY"

after_success:
  - docker build -t manishakhurana25/complex-multi-client -f ./client/Dockerfile.dev ./client
  - docker build -t manishakhurana25/complex-multi-nginx -f ./nginx/Dockerfile.dev ./nginx
  - docker build -t manishakhurana25/complex-multi-server -f ./server/Dockerfile.dev ./server
  - docker build -t manishakhurana25/complex-multi-worker -f ./worker/Dockerfile.dev ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take the prod images and push to docker hub
  - docker push manishakhurana25/complex-multi-client
  - docker push manishakhurana25/complex-multi-nginx
  - docker push manishakhurana25/complex-multi-server
  - docker push manishakhurana25/complex-multi-worker