language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -f ./client/Dockerfile.dev -t manishakhurana25/complex-multi-docker-test ./client
script:
  - docker run -e CI=true manishakhurana25/complex-multi-docker-test npm run test -- --coverage

after_success:
  - docker build -t manishakhurana25/complex-multi-client ./client
  - docker build -t manishakhurana25/complex-multi-nginx ./nginx
  - docker build -t manishakhurana25/complex-multi-server ./server
  - docker build -t manishakhurana25/complex-multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take the prod images and push to docker hub
  - docker push manishakhurana25/complex-multi-client
  - docker push manishakhurana25/complex-multi-nginx
  - docker push manishakhurana25/complex-multi-server
  - docker push manishakhurana25/complex-multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-002152815032"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"